[workspace]
name = "flowids"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
python = "3.13.*"
click = "*"
duckdb-cli = "1.5.*"
polars = "*"
pytorch = "*"
rich = "*"
basedpyright = "*"
ruff = "0.16.*"

[tasks]
convert = "python tools/scripts/convert.py"
fmt = "python tools/scripts/tools.py fmt"
clean = "python tools/scripts/tools.py clean"
lint = "python tools/scripts/tools.py lint"
model = "python tools/scripts/tools.py model"
check = { depends-on = ["fmt", "lint"] }
