[workspace]
name = "flowids"
channels = ["conda-forge"]
platforms = [{ platform = "linux-64", cuda = "12.9" }, "osx-arm64"]

[dependencies]
python = "3.13.*"
click = "*"
duckdb-cli = "1.5.*"
polars = "*"
rich = "*"
basedpyright = "*"
ruff = "0.16.*"

[target.osx-arm64.dependencies]
pytorch = "*"

[target.linux-64.dependencies]
pytorch-gpu = "*"

[tasks]
convert = "python tools/scripts/convert.py"
fmt = "python tools/scripts/tools.py fmt"
clean = "python tools/scripts/tools.py clean"
lint = "python tools/scripts/tools.py lint"
model = "python tools/scripts/tools.py model"
check = { depends-on = ["fmt", "lint"] }
