name: Checks

on:
  push:
    branches: [main, master]
    paths:
      - ".github/workflows/checks.yml"
      - "pixi.lock"
      - "pixi.toml"
      - "src/**/*.py"
      - "tools/configs/ruff.toml"
      - "tools/scripts/**/*.py"
  pull_request:
    paths:
      - ".github/workflows/checks.yml"
      - "pixi.lock"
      - "pixi.toml"
      - "src/**/*.py"
      - "tools/configs/ruff.toml"
      - "tools/scripts/**/*.py"

permissions:
  contents: read

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.10.0
        with:
          pixi-version: v0.76.2
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          frozen: true
      - run: pixi run --frozen check
